fixed   typescript  required
src/App.vue:57:17 - error TS2322: Type 'string' is not assignable to type 'boolean | undefined'.

57                 required="true"
                   ~~~~~~~~

  node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:586:3
    586   required?: boolean
          ~~~~~~~~
    The expected type comes from property 'required' which is declared here on type 'InputHTMLAttributes & ReservedProps & Omit<__VLS_GlobalAttrs, keyof ReservedProps | keyof InputHTMLAttributes> & Record<...>'

src/App.vue:72:17 - error TS2322: Type 'string' is not assignable to type 'boolean | undefined'.

72                 required="true"
                   ~~~~~~~~

  node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:586:3
    586   required?: boolean
          ~~~~~~~~
    The expected type comes from property 'required' which is declared here on type 'InputHTMLAttributes & ReservedProps & Omit<__VLS_GlobalAttrs, keyof ReservedProps | keyof InputHTMLAttributes> & Record<...>'

Found 2 errors.